sudo: required
language: node_js
node_js:
  - stable
branches:
  only:
    - master
addons:
  chrome: stable
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
  - npm install -g @angular/cli
  - npm install -g karma karma-chrome-launcher
  - npm install
script:
  - ng test --karma-config karma.container.conf.js