sudo: required
language: node_js
node_js:
- stable
branches:
  only:
  - master
addons:
  chrome: stable
services:
- xvfb
before_script:
- export DISPLAY=:99.0
- npm install -g @angular/cli
- npm install -g karma karma-chrome-launcher
- npm install
script:
- ng test --karma-config karma.container.conf.js
deploy:
  provider: heroku
  api_key:
    secure: IMAnJKtvQ6Q6K92WuUsTR9AKPicTsnt3EnGwK/2KMc6QRrmempEOg2K5gwJ/R9LYo/YGOMcIrXsW+NDTzS9fwzOdODR6cHtGxXJTPkQPKcyMzaBTgUTRkcECF8jfP1295eQO2Fcu1MQsoW2Qmow/jhCwhcB5AGgK+I10CG36R8CLmD4CxlSDOrs3wgVw9SNTAEEnLwCE3+DrEbIY+WiG9317LjJ9F3yd/RL53IT9RfoIIPyVVHdso6g1zPMav4RiVcB8tN47YmNuF/+/FdddijOoIgLP63lQxjAnEVNBd9V9A/HpkT4P9xgrud22OXWppNmiWY7RsgzD8PvcAaCrE6ZK8P9ma+LMe2gLG3WplnjQDvdG4cqGFssuhgG4GlVv1355vgV0AtXkteBM+bFzqpwFGXrWY3+8CQCgKz9E6wciZbccVpJPe2mvCrFBV7FVNHxlcuzPTARyb/I1AbIvP6lo8xeHN/Q97N07doKrSu6Y3SjgQk+ZoXHqqEd9COCY1S9eHU/Uvl9q8c0AvElVqRu6Y7bZDrKUEWaCDLKQHnwrp4eQx0XH8vRFGgQKBVLwaAcMrXChKmuzfb6uSXHp4CSOLWEKK0rBJJXF4r5q2deKeycOJ6+zvEJTN8gmxpAKyfQIGWlVEFmUzm/oN/saiP9Uu7+dCQD8N28ntfk1YEo=
  app: hidden-temple-55196
  on:
    repo: RichardPoulson/angular-heroku
  skip_cleanup: 'true'
